pcall(require, "luarocks.loader")
require("awful.autofocus")
require("awful.hotkeys_popup.keys")

require("modules/error")
require("modules/vars")
require("modules/menu")
require("modules/signals")
require("modules/rules")
require("modules/keybindings")
require("modules/wibar")
